== Functional flows for credentials

== Create a credential

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Kafka
    participant Istio
    Frontend->> Istio: POST /credentials (REST)
    Istio ->> Credential: POST /credentials (REST) + JWT Claims
    Credential->>Credential: Create a credential (Inner)
    alt Credential creation failed
        Credential-->>Frontend: 400 Credential creation failed
    else
      Credential-->>Frontend: 204 Credential created
      Credential-->>Kafka: CreateCredentialEvent (kafka)
    end
....

== Update a credential

The update action can also be done through gRPC.

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Authz service
    participant Kafka
    Frontend->>Credential: PUT /credentials/{id}

    alt User identity is not valid
          Credential-->>Frontend: 401 User identity is not valid
      else
        Credential->>Authz service: Check if can update credential
        Authz service-->>Credential: Can update credential
        alt Can update credential
            Credential->>Credential: Update a credential
            Credential->>Kafka: UpdateCredentialEvent
            note over Credential,Kafka: We won't be detailing what's happening on UpdateCredentialEvent and who are the consumers*
            Credential-->>Frontend: 200 Credential updated
        else
            Credential-->>Frontend: 403 Credential update failed
        end
    end
....

*Please refer to the organization flows since if the credential is associated to tags and those tags are updated, there will be some things happening there for sure.*

== Delete a credential

The delete action can also be done through gRPC

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Keycloak
    participant Authz service
    participant Kafka
    Frontend->>Credential: DELETE /credentials/{id}
    alt User identity is not valid
          Credential-->>Frontend: 401 User identity is not valid
      else
        Credential->>Authz service: Check if can delete credential
        Authz service-->>Credential: Can delete credential
        alt Can delete credential
            Credential->>Credential: Delete a credential
            Credential->>Kafka: DeleteCredentialEvent
            note over Credential,Kafka: We won't be detailing what's happening on DeleteCredentialEvent and who are the consumers*
            Credential-->>Frontend: 200 Credential deleted
        else
            Credential-->>Frontend: 403 Credential deletion failed
        end
    end
....

*One thing to note is that tags associated to the credential will be deleted as well. So please refer to the organization service flow to better understand this mecanism.

== Get a credential

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Agregator
    participant Credential
    participant Authz service
    participant Kafka
    Agregator->>Credential: Get batch of credentials
        Credential->>Authz service: Check if user can access credential
        Authz service-->>Credential: Credential exists
        alt Credential exists
            Credential->>Credential: Get a credential
            Credential->>Kafka: GetCredentialEvent
            note over Credential,Kafka: We won't be detailing what's happening on GetCredentialEvent and who are the consumers*
            Credential-->>Agregator: 200 Credential retrieved (credentials)
        else
            Credential-->>Agregator: 404 Credential not found
        end
....

*The insight service will surely be the one to handle the credential retrieval since they need to know how often a credential is retrieved etc.
