== Credentials

The credentials are the core of the application. They are used to store the credentials of a user/a group of users.

== Models definition

=== Credential

==== Infos

* **Title**: The title of the credential (for full text search purpose).  
* **Notes**  
* **Custom fields (optional)**

==== Type

===== Password credential

* **Identifier**: The identifier of a user on a website, this information is public.  
* **Password**: The secret key used to authenticate a user to a website  
* **Websites**: The website that the user is using to authenticate.

===== Credit card credential

* Owner name  
* CVC  
* Expiration date  
* Card number

===== Notes

* Nothing

===== Keys

* **Value :** The value of the key  
* **Passphrase :** The passphrase of the key

==== Custom fields structure

The custom fields are stored in the backend as a JSON object since it is a dynamic key value data structure. The key is the name of the custom field, and the value is the value of the custom field.

Depending on the type of the **custom field** :

* Text : the value is a string  
* Textarea: the value is a long text  
* Number : the value is a number  
* Date : the value is a string in the format "YYYY-MM-DD"  
* DateTime : the value is a string in the format "YYYY-MM-DDTHH:MM:SS"  
* Password : the hash of the password \+ salted

=== Example

[source, json]
....
{
  "username": "johndoe",
  "password": "pwd",
  "custom_fields" : {
    "Text": "lorem ipsum",
    "Textarea": "pouet.com is a website lorem ipsum"
  }
}
....

By the way, this data might be sensitive, so it should be encrypted before being stored in the backend.

== Events, pas des métadata 

4 topics, un pour chaque type d’event  
Envoie de l’id + le title (l’update doit mettre à jour le search via le title)

* Created_at
* Updated_at
* Read_at
* Deleted_at

== UML Diagram

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
classDiagram
   class Credential {
       +String title
       +String note
       +DateTime updatedAt
       +DateTime createdAt
       +DateTime lastReadAt
       +DateTime expiresAt
       +String ownerID
   }
   <<Abstract>> Credential
   class CardCredential {
       +String ownerName
       +String CVC
       +String expirationDate
       +String cardNumber
   }
   class PasswordCredential {
       +String identifier
       +String password
       +String[] websites
   }
   class Note {
   }
   class SSHKey {
       -String privateKey
       -String publicKey
   }
   class CustomField {
       +String key
   }
   CustomField "1" --> "*" CustomFieldValueType
   Credential --o CustomField
   class CustomFieldValueType {
       <<enumeration>>
       TEXT
       TEXTAREA
       NUMBER
       DATE
       DATETIME
       PASSWORD
   }
   Credential <|-- CardCredential
   Credential <|-- PasswordCredential
   Credential <|-- SSHKey
   Credential <|-- Note
....

The owner of the credential is either a user (the one that created the credential) or a group of users.

== CRUD

Create a credential  
Read a credential  
Update a credential  
Delete a credential (by name/id)

== Interaction with other services

=== Out

We interact with the authorization service to check if the user can access the credential and with the event sourcing kafka.

=== In

Query by other services
