= Functional flows for credentials

== Create a credential

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Organization
    participant Kafka
    participant Keycloak
    Frontend->>Credential: POST /credentials (REST)
    Credential->>Keycloak: Check user identity (Oauth2)
    Keycloak-->>Credential: User identity (Oauth2)
    alt User identity is not valid
          Credential-->>Frontend: 401 User identity is not valid (REST)
      else
        Credential->>Credential: Create a credential (Inner)
        Credential-->>Kafka: CreateCredentialEvent (MQTT)
        Credential-->>Organization: CreateCredentialEvent (gRPC)
        Alt Has tags or is associated to a folder
          Organization->>Organization: Create Tags, associate to folder
        End
        Alt Tags and Folder failed
            Organization-->>Kafka: CreateCredentialFailedEvent
            Kafka-->>Credential: CreateCredentialFailedEvent
            Credential->>Credential: DeleteCredential
            Credential-->>Frontend: 400 Credential creation failed
        End
        Credential-->>Frontend: 201 Credential created
    end
....

== Update a credential

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Keycloak
    participant Permify
    participant Kafka
    Frontend->>Credential: PUT /credentials/{id}

    Credential->>Keycloak: Check user identity
    Keycloak-->>Credential: User identity
    alt User identity is not valid
          Credential-->>Frontend: 401 User identity is not valid
      else
        Credential->>Permify: Check if can update credential
        Permify-->>Credential: Can update credential
        alt Can update credential
            Credential->>Credential: Update a credential
            Credential->>Kafka: UpdateCredentialEvent
            note over Credential,Kafka: We won't be detailing what's happening on UpdateCredentialEvent and who are the consumers*
            Credential-->>Frontend: 200 Credential updated
        else
            Credential-->>Frontend: 403 Credential update failed
        end
    end
....

*Please refer to the organization flows since if the credential is associated to tags and those tags are updated, there will be some things happening there for sure.

== Delete a credential

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Keycloak
    participant Permify
    participant Kafka
    Frontend->>Credential: DELETE /credentials/{id}
    Credential->>Keycloak: Check user identity
    Keycloak-->>Credential: User identity
    alt User identity is not valid
          Credential-->>Frontend: 401 User identity is not valid
      else
        Credential->>Permify: Check if can delete credential
        Permify-->>Credential: Can delete credential
        alt Can delete credential
            Credential->>Credential: Delete a credential
            Credential->>Kafka: DeleteCredentialEvent
            note over Credential,Kafka: We won't be detailing what's happening on DeleteCredentialEvent and who are the consumers*
            Credential-->>Frontend: 200 Credential deleted
        else
            Credential-->>Frontend: 403 Credential deletion failed
        end
    end
....

*One thing to note is that tags associated to the credential will be deleted as well. So please refer to the organization service flow to better understand this mecanism.

== Get a credential

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Frontend
    participant Credential
    participant Keycloak
    participant Permify
    participant Kafka
    participant Organization
    Frontend->>Credential: GET /credentials/{id}
    Credential->>Keycloak: Check user identity
    Keycloak-->>Credential: User identity
    alt User identity is not valid
          Credential-->>Frontend: 401 User identity is not valid
      else
        Credential->>Permify: Check if user can access credential
        Permify-->>Credential: Credential exists
        alt Credential exists
            Credential->>Credential: Get a credential
            Credential->>Organization: Get tags
            Organization-->>Credential: Tags
            Credential->>Kafka: GetCredentialEvent
            note over Credential,Kafka: We won't be detailing what's happening on GetCredentialEvent and who are the consumers*
            Credential-->>Frontend: 200 Credential retrieved (credentials + tags)
        else
            Credential-->>Frontend: 404 Credential not found
        end
    end
....

*The insight service will surely be the one to handle the credential retrieval since they need to know how often a credential is retrieved etc.
