= Search

We want to search by:

- tags
- credential title
- folders
- web site
- identifier
- custom fields

== Collect data
A event is call when a credential, tag and folder is created, updated or deleted. This event is used to update the search engine.

For each event we have a topic in Kafka. The topic name is the event name. 

[source,json]
----
{
    type: string;
}
----

[source,json]
----
{
    "CreateTagEvent": {
        "type": "object",
        "properties": {
            "id_tag": { "type": "string" },
            "id_folder": { "type": "string" },
            "name_tag": { "type": "string" }
        },
        "required": ["id_tag", "id_folder", "name_tag"]
    }
}
----

[source,json]
----
{
    "CreateFolderEvent": {
        "type": "object",
        "properties": {
            "id_folder": { "type": "string" },
            "name_folder": { "type": "string" }
        },
        "required": ["id_folder", "name_folder"]
    }
}
----

[source,json]
----
{
    "CreateCredentialEvent": {
        "type": "object",
        "properties": {
            "id_credential": { "type": "string" },
            "id_folder": { "type": "string" },
            "title_credential": { "type": "string" }
        },
        "required": ["id_credential", "id_folder", "title_credential"]
    }
}
----

[source,json]
----
{
    "UpdateTagEvent": {
        "type": "object",
        "properties": {
            "id_tag": { "type": "string" },
            "id_folder": { "type": "string" },
            "name_tag": { "type": "string" }
        },
        "required": ["id_tag"]
    }
}
----

[source,json]
----
{
    "UpdateFolderEvent": {
        "type": "object",
        "properties": {
            "id_folder": { "type": "string" },
            "name_folder": { "type": "string" }
        },
        "required": ["id_folder"]
    }
}
----

[source,json]
----
{
    "UpdateCredentialEvent": {
        "type": "object",
        "properties": {
            "id_credential": { "type": "string" },
            "title_credential": { "type": "string" }
        },
        "required": ["id_credential", "title_credential"]
    }
}
----

[source,json]
----
{
    "DeleteTagEvent": {
        "type": "object",
        "properties": {
            "id_tag": { "type": "string" }
        },
        "required": ["id_tag"]
    }
}
----

[source,json]
----
{
    "DeleteFolderEvent": {
        "type": "object",
        "properties": {
            "id_folder": { "type": "string" }
        },
        "required": ["id_folder"]
    }
}
----

[source,json]
----
{
    "DeleteCredentialEvent": {
        "type": "object",
        "properties": {
            "id_credential": { "type": "string" }
        },
        "required": ["id_credential"]
    }
}
----



== Search engine
This concerns tags, folders and credentials titles.

We search a credential title, a tag or a folder by name. We get all id of tags or folders with a name containing the search string and we get the list of credentials associated with it.

== Local search fields

== Architecture decisions

=== Search use-case communication flow

This could be a sequence diagram, and a use-case diagram.

1. User types a search string in the search bar.
2. Frontend fetches /search/tags
The search string is sent to the search engine. The search engine returns a list of tags, folders and credentials that match the search string.

=== Search Engine thingy

Elasticsearch

=== Events

==== Events to listen to

Resource creation events:

- Tag creation
- Credential creation
- Folder creation

==== Events to answer to

=== Database Architecture

NoSQL document database

- Tags collection
- Credentials collection
- Folder collection

{
    tag_id: String
    credential_id: String
    folder_id: String
}
