= Search

We want to search by:

- tags
- credential title
- folders
- web site
- identifier
- custom fields

== Collect data
A event is call when a credential, tag and folder is created, updated or deleted. This event is used to update the search engine.

For each event we have a topic in Kafka. The topic name is the event name. 

[source,json]
----
{
    type: string;
}
----

[source,json]
----
{
    "CreateTagEvent": {
        "type": "object",
        "properties": {
            "id_tag": { "type": "string" },
            "id_folder": { "type": "string" },
            "name_tag": { "type": "string" }
        },
        "required": ["id_tag", "id_folder", "name_tag"]
    }
}
----

[source,json]
----
{
    "CreateFolderEvent": {
        "type": "object",
        "properties": {
            "id_folder": { "type": "string" },
            "name_folder": { "type": "string" }
        },
        "required": ["id_folder", "name_folder"]
    }
}
----

[source,json]
----
{
    "CreateCredentialEvent": {
        "type": "object",
        "properties": {
            "id_credential": { "type": "string" },
            "id_folder": { "type": "string" },
            "title_credential": { "type": "string" }
        },
        "required": ["id_credential", "id_folder", "title_credential"]
    }
}
----

[source,json]
----
{
    "UpdateTagEvent": {
        "type": "object",
        "properties": {
            "id_tag": { "type": "string" },
            "id_folder": { "type": "string" },
            "name_tag": { "type": "string" }
        },
        "required": ["id_tag"]
    }
}
----

[source,json]
----
{
    "UpdateFolderEvent": {
        "type": "object",
        "properties": {
            "id_folder": { "type": "string" },
            "name_folder": { "type": "string" }
        },
        "required": ["id_folder"]
    }
}
----

[source,json]
----
{
    "UpdateCredentialEvent": {
        "type": "object",
        "properties": {
            "id_credential": { "type": "string" },
            "title_credential": { "type": "string" }
        },
        "required": ["id_credential", "title_credential"]
    }
}
----

[source,json]
----
{
    "DeleteTagEvent": {
        "type": "object",
        "properties": {
            "id_tag": { "type": "string" }
        },
        "required": ["id_tag"]
    }
}
----

[source,json]
----
{
    "DeleteFolderEvent": {
        "type": "object",
        "properties": {
            "id_folder": { "type": "string" }
        },
        "required": ["id_folder"]
    }
}
----

[source,json]
----
{
    "DeleteCredentialEvent": {
        "type": "object",
        "properties": {
            "id_credential": { "type": "string" }
        },
        "required": ["id_credential"]
    }
}
----



== Search Engine

=== What is the Search Engine?

The search engine service runs server-side. It enables finding credentials, tags and folders by name. +

==== Limitations

Since data is encrypted client-side, the search engine can't search by content, only by name.

=== Why do we need a Search Engine?

As we will see further below, the frontend is capable of locally searching for content that has been decrypted. However, data has to be [WIP] data has to be aggregated or fetched server side. Like the SE service fetches data from other services (it's a client of other services, a consumer). [/WIP]
The Search Engine runs server-side, and as such, it [WIP] [/WIP]

=== How ?

[WIP]tech stack: Go[/WIP]

This concerns tags, folders and credentials titles.

We search a credential title, a tag or a folder by name. We get all id of tags or folders with a name containing the search string and we get the list of credentials associated with it.

== Local search fields


