==== **Definition**

Sharing is a service that allows users to share secrets with guests.

* `plaintext_secret` is the content of the secret.
* `hashed_secret` is the hashed content of the secret.
* `expiration` is the date of expiration of the secret in Unix timestamp.
* `is_one_time_use` is a boolean that indicates if the secret can only be seen once.
* `created_at` is the date of creation of the secret.
* `id` is the identifier of the secret.

In your payload you will have either plaintext_secret or hashed_secret but not both.

Refer to the link:./lexicon.adoc[lexicon] for more information about the terms used in this interface.

==== **Interfaces**

===== __Sharing a secret__

****
Message
[source,json]
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "plaintext_secret": {
      "type": "string",
      "description": "The secret in plaintext form. Should not be provided if 'hashed_secret' is present."
    },
    "hashed_secret": {
      "type": "string",
      "description": "The hashed version of the secret. Should not be provided if 'plaintext_secret' is present."
    },
    "expiration": {
      "type": "integer",
      "description": "Unix timestamp indicating the expiration time of the secret.",
      "minimum": 0
    },
    "is_one_time_use": {
      "type": "boolean",
      "description": "Indicates whether the secret can only be used once."
    }
  },
  "required": ["expiration", "is_one_time_use"],
  "oneOf": [
    { "required": ["plaintext_secret"], "not": { "required": ["hashed_secret"] } },
    { "required": ["hashed_secret"], "not": { "required": ["plaintext_secret"] } }
  ],
  "additionalProperties": false
}
----
****


****
Response
[source,json]
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "created_at": {
      "type": "integer",
      "description": "Unix timestamp indicating when the object was created.",
      "minimum": 0
    },
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "Unique identifier for the object, represented as a UUID."
    },
  },
  "required": ["created_at", "id"],
  "additionalProperties": false
}
----
****

===== __Getting a secret__

****
Message
[source,json]
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "Unique identifier for the object, represented as a UUID."
    },
  },
  "required": ["id"],
  "additionalProperties": false
}
----
****

****
Response
[source,json]
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "Unique identifier for the object, represented as a UUID."
    },
    "plaintext_secret": {
      "type": "string",
      "description": "The secret in plaintext form. Must not be provided if 'hashed_secret' is present."
    },
    "hashed_secret": {
      "type": "string",
      "description": "The hashed version of the secret. Must not be provided if 'plaintext_secret' is present."
    }
  },
  "required": ["id"],
  "oneOf": [
    { "required": ["plaintext_secret"] },
    { "required": ["hashed_secret"] }
  ],
  "additionalProperties": false
}
----
****

==== **Sequence Diagram**

===== __User's client__

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant User's client
    participant Sharing API
    participant Kafka

    alt the secret needs to be hashed
        User's client->>User's client: Create a hash
    end
    
    User's client->>Sharing API: Send the secret

    Sharing API->>Sharing API: Store the secret

    Sharing API->>Kafka: Send analytics metrics

    Sharing API-->>User's client: Send the secret id
....

===== __Guest's client__

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant Sharing API
    participant Guest's client
    participant Kafka

    Guest's client->>Sharing API: Request the secret
    Sharing API->>Kafka: Send analytics metrics
    
    alt the secret one time use
        Sharing API->>Sharing API: Delete the secret
        Sharing API->>Kafka: Send analytics metrics
    end

    Sharing API-->>Guest's client: Send the secret
    
    alt the secret is hashed
        Guest's client->>Guest's client: Decrypt the hash
    end

    alt copying the secret
        Guest's client->>Sharing API: Send a copying request
        Sharing API->>Kafka: Send analytics metrics
    end
....

==== **Cron**

A cron job is responsible for deleting secrets with an expiration date. The cron's execution date is set to the nearest secret expiration date.
